version: "3.8"

networks:
  node-net:
    driver: bridge

volumes:
  mysql_data:
    external: false

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    networks:
      - node-net
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: "nodedb"
      MYSQL_USER: "nodeuser"
      MYSQL_PASSWORD: "nodepwd"
      MYSQL_ROOT_PASSWORD: "nodepwd"
    healthcheck:
      test: echo $$MYSQL_PASSWORD | mysqladmin ping -h localhost -u $$MYSQL_USER -p 
      interval: 2s
      timeout: 5s
      retries: 10

  app:
    image: api
    build:
      context: node
      dockerfile: Dockerfile
    container_name: app
    restart: always
    networks:
      - node-net
    environment:
      PORT: 3000
    healthcheck:
      test: wget -nv -t1 --spider "http://localhost:$$PORT/healthz" || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    networks:
      - node-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    healthcheck:
      test: curl --fail http://localhost/healthz || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      app:
        condition: service_healthy
