version: "3.8"

networks:
  node-net:
    driver: bridge

volumes:
  mysql_data:
    external: false

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    networks:
      - node-net
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: "nodedb"
      MYSQL_USER: "nodeuser"
      MYSQL_PASSWORD: "nodepwd"
      MYSQL_ROOT_PASSWORD: "nodepwd"

  app:
    image: api
    build:
      context: node
      dockerfile: Dockerfile
    container_name: app
    restart: always
    networks:
      - node-net
    depends_on:
      - mysql

  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    networks:
      - node-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - app
